version: "3"

services:
  moneyapp-postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${money_app}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
